default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db
  username: postgres
  password: password

test:
  <<: *default
  database: da8d67d1vab7bv
  username: kaytengnhpvktz
  password: ebc2092973415cf68afbdeebe5737ce9ba874f31eb8d9a5340ef4c762830ed07

production:
  <<: *default
  database: da8d67d1vab7bv
  username: kaytengnhpvktz
  password: ebc2092973415cf68afbdeebe5737ce9ba874f31eb8d9a5340ef4c762830ed07