default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_circleci_heroku_example_development
  username: faizalrakhman
  password:

test:
  <<: *default
  database: ruby_circleci_heroku_example_test
  username: faizalrakhman
  password:

production:
  <<: *default
  database: ruby_circleci_heroku_example_production
  username: ruby_circleci_heroku_example
  password: <%= ENV['RUBY_CIRCLECI_HEROKU_EXAMPLE_DATABASE_PASSWORD'] %>
